apiVersion: v1
kind: Namespace
metadata:
  name: camel-k-test
  labels:
    name: camel-k-test
---
apiVersion: v1
kind: Namespace
metadata:
  name: camel-k-prod
  labels:
    name: camel-k-prod
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: camel-k-operator
  namespace: operators
spec:
  channel: latest
  name: camel-k
  source: operatorhubio-catalog
  sourceNamespace: olm
